/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aps.loop.java.apresentacao;

import aps.loop.java.modelo.Cena;
import aps.loop.java.modelo.ControleCena;
import aps.loop.java.modelo.Escolha;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class JpnCena extends javax.swing.JPanel
{

    
    private ControleCena controleCena;
    private Cena cena;
    
    /**
     * Creates new form JpnCena
     */
    
    public JpnCena()
    {
        initComponents();
        try
        {
            this.limpar();
            this.controleCena = new ControleCena();
            this.cena = this.controleCena.cena;
            
            String lerCena = this.cena.lerCena(this.cena.getInicial());
            
            if(this.cena.montaCena(lerCena));
            {
                setTextCena();
            }
           
        } catch (Exception ex)
        {
            Logger.getLogger(frmGame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        txaHistoria = new javax.swing.JTextArea();
        btnOpcao1 = new javax.swing.JButton();
        btnOpcao2 = new javax.swing.JButton();

        txaHistoria.setColumns(20);
        txaHistoria.setLineWrap(true);
        txaHistoria.setRows(5);
        txaHistoria.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaHistoria);

        btnOpcao1.setText("perguntar por uma saída");
        btnOpcao1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpcao1ActionPerformed(evt);
            }
        });

        btnOpcao2.setText("perguntar por uma saída");
        btnOpcao2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOpcao2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnOpcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOpcao1)
                    .addComponent(btnOpcao2))
                .addContainerGap(13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcao1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpcao1ActionPerformed
    {//GEN-HEADEREND:event_btnOpcao1ActionPerformed
        this.executaEscolha(0);
        setTextCena();
    }//GEN-LAST:event_btnOpcao1ActionPerformed

    private void btnOpcao2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOpcao2ActionPerformed
    {//GEN-HEADEREND:event_btnOpcao2ActionPerformed
        this.executaEscolha(1);
        setTextCena();
    }//GEN-LAST:event_btnOpcao2ActionPerformed

    private void limpar()
    {
        this.txaHistoria.setText("");
        this.btnOpcao1.setText("");
        //this.btnOpcao1.setBounds(50, 247, 134, 32);
        this.btnOpcao1.setVisible(false);
        this.btnOpcao2.setText("");
        this.btnOpcao2.setVisible(false);

    }
    
    private void setTextCena()
    {
        this.limpar();
        
        this.txaHistoria.setText(this.cena.getHistoria());
        txaHistoria.setCaretPosition(0);
        List<Escolha> escolhas = this.cena.getEscolhas();
        int sizeEscolhas = escolhas.size();
               
        if(0 < sizeEscolhas)
        {
            Escolha get = escolhas.get(0);
            btnOpcao1.setText(get.getNome());
            btnOpcao1.setVisible(true);
        }
        
        if(1 < sizeEscolhas)
        {
            Escolha get = escolhas.get(1);
            btnOpcao2.setText(get.getNome());
            btnOpcao2.setVisible(true);
        }
        
    }
    
    private void executaEscolha(int num)
    {
        try
        {
            controleCena.executaEscolha(num);
        } catch (Exception ex)
        {
            Logger.getLogger(frmGame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpcao1;
    private javax.swing.JButton btnOpcao2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txaHistoria;
    // End of variables declaration//GEN-END:variables
}
